[build]
  base = "frontend"
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://chef-garage-system.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200